create table PAC4J_CFG
(
  SSPCC_ID IDENTITY NOT NULL,
  CLIENT_NAME VARCHAR(200) NOT NULL,
  ENVIRONMENT VARCHAR(20) NOT NULL,
  KEYSTORE_DATA BLOB NOT NULL,
  KEYSTORE_PASSWORD VARCHAR(50),
  PRIVATE_KEY_PASSWORD VARCHAR(50),
  IDP_METADATA CLOB NOT NULL,
  IDP_ENTITY_ID VARCHAR(200) NOT NULL,
  SP_ENTITY_ID VARCHAR(200) NOT NULL,
  MAX_AUTH_LIFETIME INT DEFAULT 3600 NOT NULL,
  DEST_BINDING_TYPE VARCHAR(200),
  CONSTRAINT PAC4J_CFG_PK PRIMARY KEY (SSPCC_ID),
  CONSTRAINT PAC4J_CFG_UK1 UNIQUE (CLIENT_NAME,ENVIRONMENT),
  CONSTRAINT PAC4J_CFG_CHK1 CHECK (MAX_AUTH_LIFETIME > 0)
);
